---
# Configure the jenkins resources
- name: Configure the jenkins-Route
  ansible.builtin.command:
    cmd: "oc apply --filename=- --namespace={{ adrianjuhl__jenkins_on_openshift4__openshift_namespace_jenkins }}"
  changed_when: false
  args:
    stdin: "{{ lookup('file', 'jenkins-Route.yaml') }}"
- name: Configure the jenkins-trusted-ca-bundle-ConfigMap
  ansible.builtin.command:
    cmd: "oc apply --filename=- --namespace={{ adrianjuhl__jenkins_on_openshift4__openshift_namespace_jenkins }}"
  changed_when: false
  args:
    stdin: "{{ lookup('file', 'jenkins-trusted-ca-bundle-ConfigMap.yaml') }}"
- name: Configure the jenkins-PersistentVolumeClaim
  ansible.builtin.command:
    cmd: "oc apply --filename=- --namespace={{ adrianjuhl__jenkins_on_openshift4__openshift_namespace_jenkins }}"
  changed_when: false
  args:
    stdin: "{{ lookup('file', 'jenkins-PersistentVolumeClaim.yaml') }}"
- name: Configure the jenkins-DeploymentConfig
  ansible.builtin.command:
    cmd: "oc apply --filename=- --namespace={{ adrianjuhl__jenkins_on_openshift4__openshift_namespace_jenkins }}"
  changed_when: false
  args:
    stdin: "{{ lookup('file', 'jenkins-DeploymentConfig.yaml') }}"
- name: Configure the jenkins-ServiceAccount
  ansible.builtin.command:
    cmd: "oc apply --filename=- --namespace={{ adrianjuhl__jenkins_on_openshift4__openshift_namespace_jenkins }}"
  changed_when: false
  args:
    stdin: "{{ lookup('file', 'jenkins-ServiceAccount.yaml') }}"
- name: Configure the jenkins_edit-RoleBinding
  ansible.builtin.command:
    cmd: "oc apply --filename=- --namespace={{ adrianjuhl__jenkins_on_openshift4__openshift_namespace_jenkins }}"
  changed_when: false
  args:
    stdin: "{{ lookup('file', 'jenkins_edit-RoleBinding.yaml') }}"
- name: Configure the jenkins-jnlp-Service
  ansible.builtin.command:
    cmd: "oc apply --filename=- --namespace={{ adrianjuhl__jenkins_on_openshift4__openshift_namespace_jenkins }}"
  changed_when: false
  args:
    stdin: "{{ lookup('file', 'jenkins-jnlp-Service.yaml') }}"
- name: Configure the jenkins-Service
  ansible.builtin.command:
    cmd: "oc apply --filename=- --namespace={{ adrianjuhl__jenkins_on_openshift4__openshift_namespace_jenkins }}"
  changed_when: false
  args:
    stdin: "{{ lookup('file', 'jenkins-Service.yaml') }}"
