---
# Ensure that the oc client is currently connected to the expected openshift server
- name: Verify that the oc client is currently connected to the expected server
  ansible.builtin.command:
    cmd: oc whoami --show-server
  check_mode: false  # run task always (regardless of whether the '--check' parameter is used)
  changed_when: false
  ignore_errors: true
  register: adrianjuhl__jenkins_on_openshift4__current_openshift_server_url
- name: Exit if the server currently connected to is not the expected one
  ansible.builtin.fail:
    msg: "The oc client is not connected to the expected server (current: {{ adrianjuhl__jenkins_on_openshift4__current_openshift_server_url.stdout }}, expected: {{ adrianjuhl__jenkins_on_openshift4__openshift_server_url }})"
  when: adrianjuhl__jenkins_on_openshift4__current_openshift_server_url.stdout != adrianjuhl__jenkins_on_openshift4__openshift_server_url
