apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: jenkins-persistent
    config.openshift.io/inject-trusted-cabundle: "true"
    template: jenkins-persistent-template
  name: jenkins-trusted-ca-bundle
