apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: jenkins-persistent
    template: jenkins-persistent-template
  name: jenkins-agent-maven-dotm2-directory
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status: {}
